### ISSUE TITLE
Hello, thank you for the sharing of Efi, can I use this efi in x250? thanks ..

### ISSUE THREAD

**Issue by fAlkon35** [HBlanqueto/T480-hackintosh#1]

**Comment by fAlkon35** [comment]
Hello, thank you for the sharing of Efi, can I use this efi in x250? thanks ..

**Comment by HBlanqueto** [comment]
Hello, I've been researching at your model, is [this your ThinkPad](https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_X250/ThinkPad_X250_Spec.PDF)?

If that is the case, It won't be possible to use the EFI from this repo due to intel generations are different and the SSDT files too, however I took my time to search if there is a repository for your model and I found this:

- [Lenovo-ThinkPad-X250-Hackintosh by zamprjkt](https://github.com/zamprjkt/Lenovo-Thinkpad-X250-Hackintosh)

It's more probably that could work in your ThinkPad, give I try. I wish this could help you and good luck!

**Comment by fAlkon35** [comment]
yes the model is true.

CPU
1x Intel Core i5-5200U Processor(I5-5200U)
RAM
1x 8GB PC3-12800
Wifi
1x Intel Wireless 7265AC(2x2)+BT4.0 M.2 Combo; Bluetooth® 4.0
GPU
1x Intel HD 5500

Thank you for your interest, and I noticed that the Efi de OpenCore (v0.8.6) you suggested was quite old. Since your efi is more up to date (V0.9.4) I wanted to consult you to use it. Thank you again..

**Comment by HBlanqueto** [comment]
Oh sure, go ahead! I would like to know If you make It work in your computer :)

A tip I could give you in order to makes things easier for you is to use the EFI from zamprjkt and install Monterey and then, when you have installed the system in your computer, using [Hackintool](https://github.com/benbaker76/Hackintool) app and [Sanity Checker](https://sanitychecker.ocutils.me/) to update kext and OC from that repository.

- Hackintool will help you to download latest kext and OpenCore, you will need to replace the appropiate files to have them up to date.
- Checking zamprjkt EFI, I saw he uses HeliPort but I would prefer to change that kext with [Airportlwm](https://github.com/OpenIntelWireless/itlwm/releases), do this after installing the system.
- Sanity Checker can help you to compare the old config.plist file from that repo with the latest in order to add or remove any value in that file.

This is something a friend did with his Dell Vortrex in order to use Ventura, the repo from he based used an old OpenCore version so he just updated all with this.

**Comment by fAlkon35** [comment]
I will try very much ..
