### ISSUE TITLE
ThinkPad T580 Ventura 13.5

### ISSUE THREAD

**Issue by rvlphee** [HBlanqueto/T480-hackintosh#2]
![Screenshot 2023-08-19 at 8 34 03 PM](https://github.com/HBlanqueto/T480-hackintosh/assets/68458218/9990433a-ed11-4a2b-aeef-efb2d4961e21)
Installed onto Hynix 256gb (HFM256GDHTNG-8510B) M2 ssd in WWAN slot. 
Everything working except AirDrop.

**Comment by HBlanqueto** [comment]
Hi! I'm glad to see It's working, about AirDrop as far as I know It doesn't work in the Intel wifi cards, so that's the only issue I've seen in other EFI that use Intel cards.

Before closing this issue and adding in the README.md the compatibility with this ThinkPad, I want to ask you 2 questions.

1. How is the battery performance in your ThinkPad?
2. Is the thunderbolt working?

It's suppose that CPUFriendData.kext I chaged using [Dortania's guide](https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#lfm-low-frequency-mode) has 'Power saving' configuration so I wanted to know If you feel the battery is not drained quickly, in my case the T480 I bought by second hand my battery has already past life time and does not last long or It's just something about macOS.

For the ThunderBolt, is It enabled or showing in the 'System Report' app?

**Comment by rvlphee** [comment]
Hi! Thank you for information about AirDrop and intel wifi cards. Been pretty curious about this. 

1. Bought my thinkpad second handed too, battery health been aroud 86%. I feel like battery last longer then on windows (both system have enabled power saving modes). 
2. If i plug in regular USB device using type c - USB 2.0 dongle it works as usual. To be honnest, i dont have a thunderbolt device to test out. Thats what System Information app says. 
![Screenshot 2023-08-20 at 1 19 45 PM](https://github.com/HBlanqueto/T480-hackintosh/assets/68458218/c74def4c-8e7e-4669-b272-9a72af39cc72)
